language: java

jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -e -B
  - if [[ $TRAVIS_PULL_REQUEST -ne 'false' ]]; then mvn sonar:sonar -Dsonar.host.url=http://nemo.sonarqube.org -Dsonar.analysis.mode=preview; fi

install: true

after_success:
  - if [[ $TRAVIS_PULL_REQUEST -ne 'false' ]]; then wget https://www.googledrive.com/host/0B-fS5IyruhUSZEFEQ2doVllzVkU -O sq-github.jar; fi
  - if [[ $TRAVIS_PULL_REQUEST -ne 'false' ]]; then java -jar sq-github.jar henryju-test/sonar-build-stability target/sonar/sonar-report.json "${TRAVIS_PULL_REQUEST}"; fi

sudo: false

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
before_cache:
    - find ~/.m2 -name *SNAPSHOT -type d | xargs rm -rf

notifications:
  email: false
